# 记录各SD的记录器设置文件
[Common]

  #
  S_Assigned_SD=3-1,4-1,5-1,6-1
  #在单个文件中的行数
  Lines_per_File=6000
  #在记录文件中预先跳过的记录数 default=800
  JumpOverCount=800
  #合并记录文件时开始的文件序号位置-从1开始
  JointStartPos=1
  #合并记录的总行数
  JointLineCounts=300000